### ISSUE TITLE
Reboot?

### ISSUE THREAD

**Issue by asbjornenge** [bakenetwork/BakeNetwork#1]
Hey!

Any plans to reboot this project? Great idea and super useful for smaller bakers (like myself) 😉 If not, do you know of any similar projects out there?

Kind regards,
Asbjørn

**Comment by KevinMehrabi** [comment]
It's coming up. We're applying for an ecosystem grant.

**Comment by KevinMehrabi** [comment]
Also it's bakepool now

**Comment by asbjornenge** [comment]
Bakepool, found it, thanks! 👍 Good luck getting a grant 🚀
